### ISSUE TITLE
When setting up custom CONTEXT it wipes the default context inhereted from the template

### ISSUE THREAD

**Issue by titansmc** [OpenNebula/terraform-provider-opennebula#10]
Hi,
when deploying VMs with the following snippet, the CONTEXT of the VM is gone and only what I have defined through the terraform is present, but the defaults from the "VM template" I am using are gone.
```
# data "template_file" "cloudinit" {
#  template = "${file("cloud-init.yaml")}"
#}

resource "opennebula_virtual_machine" "demo" {
  count = 1
  name = "kubespray1-${count.index}"
  cpu = 2
  vcpu = 2
  memory = 2024
  permissions = "660"
  template_id = 2

  context = {
    NETWORK = "YES"
    SET_HOSTNAME = "$NAME"
    USER_DATA = "${data.template_file.cloudinit.rendered}"
    START_SCRIPT = "yum install -y git"
  }

  graphics {
    type = "VNC"
    listen = "0.0.0.0"
  }

  os {
    arch = "x86_64"
    boot = "disk0"
  }

  disk {
    image_id = 1
    size = 10000
    target = "vda"
    driver = "qcow2"
  }

  nic {
#    model = "virtio-pci-net"
    network_id = 1
  }
}

output "vm_ips" {
  value = "${join(",",opennebula_virtual_machine.demo.*.ip)}"
```

**Comment by jaypif** [comment]
Hi @titansmc 

Indeed. that's by design. It override the context part of a template.
I think you want to merge both.

There are some new helpers to manage easily structure into the goca since the last version. But there not used yet.
Until now it was not possible to marge CONTEXT easily so the idea was to override the CONTEXT if it is provided in the VM.

In your case, I invite you to put all variables into the VM directly until a fix is available.

It is not clear yet when it will be the case

Regards

**Comment by treywelsh** [comment]
@titansmc if you want to give it a try I made some changes to enable this behavior:
- take the keys from the template context part
- override context keys with them from the VM

These changes are on top of some other changes we need to do to update the provider (See PR #13 it's under review).
It seems ok to me, but feel free to leave a comment :)

NOTE: It miss a test case to create a VM using a template (via `template_id` attribute), with some more checks on the context overriding. It depends on #12 to add template creation for test purposes.

**Comment by treywelsh** [comment]
Added by #13 
Feel free to reopen the issue if something wrong :)
