### ISSUE TITLE
Disks not properly recorded in state file when used in dynamic block

### ISSUE THREAD

**Issue by hbuttguavus** [OpenNebula/terraform-provider-opennebula#125]
I have an issue where the state file is recording the incorrect target and size for my disk in the dynamic disk block i have. The VM is created correctly and there are no issues when I run terraform for the first time. Any subsequent terraform updates I want to do result in an error.

main.tf
```
data "template_file" "vm_template_file" {
  template = file("${path.module}/${var.vm_template}")
  vars = {
    VM_LABELS = "${var.labels},${var.cluster_name},node_exporter"
    CLUSTER_NAME = var.cluster_name
    VM_DATASTORE = var.vm_datastore
  }
  depends_on = [var.ssh_pub_key]
}

resource "opennebula_template" "vm_template" {
  name = var.vm_name
  template = data.template_file.vm_template_file.rendered
  permissions = "660"
}

resource "opennebula_virtual_machine" "vm" {
  count = var.vm_count
  permissions = "660"
  pending = var.vm_pending
  name = var.vm_count == 1 && var.vm_pending ? var.vm_name : "${var.vm_name}-${format("%02d", count.index+1)}"

  template_id = opennebula_template.vm_template.id

  cpu = var.cpu
  vcpu = var.cpu
  memory = var.memory

  os {
    arch = "x86_64"
    boot = ""
  }

  context = {
    NETWORK = "YES"
    REGISTER_DNS = "YES"
    REPORT_READY = "YES"
    SSH_PUBLIC_KEY = var.ssh_pub_key
    SET_HOSTNAME = "${var.vm_name}-${format("%02d", count.index+1)}${var.domain}"
    USERNAME = "${var.vm_username}"
    START_SCRIPT_BASE64 = var.enable_freeipa_client ? "${filebase64("${path.module}/${var.enable_freeipa_client_script}")}" : null
  }

  graphics {
    type = "VNC"
    listen = "0.0.0.0"
  }

  disk {
    image_id = var.os_disk_imageid
    size = var.os_disk_size
    driver = var.os_disk_driver
    target = var.os_disk_target
  }

  dynamic "disk" {
    for_each = var.extra_disks
    content {
      image_id = disk.value["image_id"]
      size = disk.value["size"]
      driver = disk.value["driver"]
      target = disk.value["target"]
    }
  }

  nic {
    network_id = var.network_id
  }

  timeout = var.timeout
}
```

Example dynamic disks var:

```
extra_disks_k8s_wrk = [
  {
    size     = 102400
    image_id = 11
    target   = "vdb"
    driver   = "raw"
  },
  {
    size     = 204800
    image_id = 11
    target   = "vdc"
    driver   = "raw"
  }
]
```

Statefile excerpt:
```
...
"disk": [
              {
                "computed_driver": "raw",
                "computed_size": 102400,
                "computed_target": "vda",
                "disk_id": 0,
                "driver": "raw",
                "image_id": 55,
                "size": 102400,
                "target": "vda"
              },
              {
                "computed_driver": "raw",
                "computed_size": 102400,
                "computed_target": "vdb",
                "disk_id": 1,
                "driver": "raw",
                "image_id": 11,
                "size": 102400,
                "target": "vdb"
              },
              {
                "computed_driver": "raw",
                "computed_size": 204800,
                "computed_target": "vdc",
                "disk_id": 2,
                "driver": "raw",
                "image_id": 11,
                "size": 102400,
                "target": "vdb"
              }
            ],
...
```

Change that causes an error that I did not want:
```
...
      ~ disk {
          ~ size            = 102400 -> 204800
          ~ target          = "vdb" -> "vdc"
            # (6 unchanged attributes hidden)
        }
...
```

Let me know if I can provide any more info.

**Comment by treywelsh** [comment]
EDIT:
It's a misconception in the provider if we consider that it's ok to attach an image twice to a VM.
What is the use case ?

The reason of this problem is: the provider use the `image_id` to identify a disk in some code parts so here the provider is confused between the two disks.
A disk has it's own identifier `disk_id` which should probably be used instead, or maybe a check on `target` should be added in addition to the `image_id`.
This also impact `nic` in the same way with `network_id`
I'll made some tests to see if I can fix this easily

**Comment by hbuttguavus** [comment]
I have an empty block storage defined as disk id 11 in my opennebula. If I want to add a disk to a vm I simply add this disk defining the size I want. I guess a workaround would be to have another one defined that I can use for a second disk that I want to add to the same vm. 
I have not tried adding this disk twice to the same VM before until recently. Actually not sure if there are any repercussions for using the same image as a second disk.

OpenNebula Image I am using:
<img width="402" alt="Screen Shot 2021-05-30 at 3 25 09 AM" src="https://user-images.githubusercontent.com/47117704/120096092-7bb75680-c0f7-11eb-8b06-2daf36be8464.png">

**Comment by treywelsh** [comment]
Hi,

[Here is my development branch](https://github.com/treywelsh/terraform-provider-opennebula/tree/fix_image_attached_twice), I tested it a bit and it seems better for your use case, and CI tests passes.
Feel free to test it in tricky use cases, make it fail, and give me feedback, it's not perfect but if it's good enough I'll probably make a PR.
By "not perfect" I mean for instance: trying some update could show broken diff (but with expected behavior at apply), or some tricky test case with a template may still make things fail.

And last, my global feeling during my tests: having an additional resource that represent the attachment of an image to a VM (or a disk) would make things easier from terraform point of view than managing a list of disks and trying to filter the list to retrieve a disk.
