### ISSUE TITLE
Cannot Update Context Vars on running VM via Terraform

### ISSUE THREAD

**Issue by MEGrimshaw** [OpenNebula/terraform-provider-opennebula#134]
When I go into the Sunstone UI I can update context variables & validate the change on the VM, however, when doing this via Terraform results in TF showing the change was successfully made, however that change isn't reflected either in the UI nor on the VM.

There's a similar (Open) issue here: https://github.com/OpenNebula/terraform-provider-opennebula/issues/63#issuecomment-826873026

However, the discussion around that thread is that it isn't possible.  We have verified it's possible in the UI, just not via Terraform.

**Comment by MEGrimshaw** [comment]
Still digging into the code, but it appears as though in `func resourceOpennebulaVirtualMachineUpdate` there is nothing looking for changes to the context vars.  Name, Permissions, Group, Tags, Disk & Nic but not context.

**Comment by jaypif** [comment]
Hi all

This issue is the same as #63. 

You are right about the observed behavior for context attributes.
When the first release of the provider was developed it was not possible to "hot" update the context. 
Since 5.10 release it is indeed possible but the provider was not updated.

I propose to close this issue and to continue on #63.

Thank you for your contribution.

Best regards
