### ISSUE TITLE
merging/updating tags and context metadata

### ISSUE THREAD

**Issue by rockpapergoat** [OpenNebula/terraform-provider-opennebula#175]
not sure if this has already been addressed in the master branch. i'm using the public 0.3.0 release of this module for now in a wrapper module. these are setup as locals:

```
  vm_ssh_context = {
    SSH_PUBLIC_KEY = "${var.one_username}[SSH_PUBLIC_KEY]"
  }
  vm_extra_context = {}
  vm_context       = local.vm_extra_context != {} ? merge(var.vm_default_context, local.vm_ssh_context, local.vm_extra_context) : merge(local.vm_ssh_context, var.vm_default_context)

  extra_tags = {}
  tags       = local.extra_tags != {} ? merge(var.default_tags, local.extra_tags) : var.default_tags
```

is this conf update addressed in #145 ?

i basically need to set default values for things but allow overriding via map merging for users to include arbitrary metadata. the terraform `merge()` function yields the desired results, but the provider somehow doesn't. we have multiple open nebula clusters setup, all in the 5.x version range.

if there's a better/approved way to approach things like this, please let me know.

also, will there be an updated public release of this provider any time soon?

thanks,

nate

**Comment by rockpapergoat** [comment]
i'll close this after figuring out the proper use of locals and merging. is this the best place to get feedback/help? the open nebula forum has been kind of dead. where is the community?

**Comment by treywelsh** [comment]
It's the right place to get some help around the OpenNebula terraform provider.

I understand your frustration, I'm one of the maintainers but I work for an other company and I didn't answer you because at first glance, I'm not enough confident with terraform higher level stuff like modules and functions.
It would take me more time than usual to answer you and I'm already working to add new capabilities to the provider.

Feel free to continue to open new issues related to the provider here, somebody may be able to help you

**Comment by rockpapergoat** [comment]
thanks for your answer and working on the provider. i think the ecosystem could really use solid terraform/provisioning support.
