### ISSUE TITLE
Add support for services

### ISSUE THREAD

**Issue by knfoo** [OpenNebula/terraform-provider-opennebula#18]
It would be very use full to have the ability to handle services with terraform.
It is not listed in either the resources or limitations in the readme.
Is it already working ?

**Comment by knfoo** [comment]
It is not listed in either the resources or limitations in the readme.
Is it already working ?

**Comment by treywelsh** [comment]
Hi,

Thank you for your issue :)

No, for now there is nothing implemented to manages services in the OpenNebula provider.

As far as I know, we didn't planned to add this soon. Maybe later @jaypif ?

Technically, to better understand the work to to do, I took a look at the part of the OpenNebula API that manage the services.
I did a bit of reverse, so please @christian7007 don't hesistate to correct me if I misunderstood something.

Services are not a "basic" resources like host, VM, user etc.
It would require a bit more of work to implement the ability of managing services via the provider, than for other resources, at least because we don't have anything implemented to manage them.

In brief, services does not have dedicated XML-RPC API methods, and don't have any related code in Goca (Go bindings on top of XML-RPC API).
Services lives on top of the `document` API (with document ID 100 and 101), and they have their data stored in json format.

[See the official documentation of the XML-RPC API for ONE 5.10](https://docs.opennebula.org/5.10/integration/system_interfaces/api.html)
[See service documentation](https://docs.opennebula.org/5.10/advanced_components/application_flow_and_auto-scaling/appflow_use_cli.html)

I suppose that at least, it miss some code to help us to manage services as:
- data mapping:
  - json structures to (un)marshal the service content
  - role states
- some methods that use `document` calls

**Comment by christian7007** [comment]
Yes, as @treywelsh said is not that easy to include service management inside GOCA as OneFlow is a separate component interfaced via REST API not XML-RPC.

If you are working on that @treywelsh, don't hesitate to contact me and we can discuss how to include this in GOCA.

**Comment by knfoo** [comment]
OK

Thank you for the detailed answer.
