### ISSUE TITLE
Public cloud in opennebula template

### ISSUE THREAD

**Issue by perrfect** [OpenNebula/terraform-provider-opennebula#186]
Hello.
I need use AWS provider in a opennebula template.
But the block of type "PUBLIC_CLOUD" doesn't work in terraform.
Іs this option supported?

**Comment by jaypif** [comment]
HI, 

I don't understand your need.
AWS provider is AWS provider. It is useful to manage AWS infra and service directly on AWS. It can't be use inside OpenNebula.

Do you mean you want to manage AWS resource via OpenNebula and in that case you need to deploy EC2 instances instead of VM on KVM or vcenter ?

Can you share more details on your need please ?

Thanks

**Comment by perrfect** [comment]
Hi, thank you for your reply.
I want to create hybrid template and to be able to create ec2 instances via Opennebula.
For that Opennebula has **Amazon EC2 Driver**

```
 public_cloud = {
    AMI          = "ami-030e490"
    HOST         = "5"
    INSTANCETYPE = "t2.micro"
    TYPE         = "ec2"
  }
```

When I use this driver in template via Opennebula GUI everything is fine, but when i use **public_cloud** in terraform i get an error.

`│ An argument named "public_cloud" is not expected here.`

**Comment by jaypif** [comment]
Hi,

Indeed this is not supported for the moment. 

I can't give you an ETA about this yet.

**Comment by treywelsh** [comment]
It seems there was some changes around `PUBLIC_CLOUD` in the documentation: in 6.4 OpenNebula documentation `PUBLIC_CLOUD` doesn't seems to be documented anymore:

- [see 5.12 ONE doc](https://docs.opennebula.io/5.12/search.html?q=PUBLIC_CLOUD&check_keywords=yes&area=default)
- [see 6.4 ONE doc](https://docs.opennebula.io/6.4/search.html?q=PUBLIC_CLOUD&check_keywords=yes&area=default)

This change already appear from 6.0. Reading [6.0 release note on what happened](https://docs.opennebula.io/6.0/intro_release_notes/release_notes/whats_new.html#distributed-edge-provisioning) this seems to be related to the the introduction of edge, provider etc. notions: 
```text
These new edge features in OpenNebula 6.0 include:
...
- A fully-featured command line interface and a modern, slick web interface—FireEdge—to easily manage
  public cloud and edge providers, as well as the seamless provisioning of OpenNebula’s Edge Clusters.
  You can quickly expand your OpenNebula cloud on demand with third-party resources thanks to this
  point and click interface and create an “Edge as a Service” environment in just a few minutes!
- A first set of templates and drivers to expand your OpenNebula cloud using AWS and Equinix Metal resources,
  creating Edge Clusters based on LXC, KVM, and Firecracker.
...
```
Here is the documentation [6.4 documentation around Edge an cloud provider](https://docs.opennebula.io/6.4/provision_clusters/providers/index.html)


Not sure this issue is still relevant with the `PUBLIC_CLOUD` attribute.

**Comment by treywelsh** [comment]
@perrfect @frousselet @christian7007 regarding my last comment, and if I'm right, what should we do with this ?

- Does anyone used these features from the 6.0 release of OpenNebula ?
- is this issue still in the scope of the provider ? (is it still possible from XML-RPC via custom attributes etc. to act on public clouds ?)

If I have time I'll take a look but any other input is welcomed

**Comment by treywelsh** [comment]
Some definitions:
```
A Provider represents a Cloud where resources (hosts, networks or storage) are allocated to implement
a Provision. Usually a Provider includes a zone or region in the target Cloud and an account that
will be used to create the resources needed.
```

It seems that provider management rely on "meta"-resource document (which has some XML-RPC methods): 

- https://github.com/OpenNebula/one/blob/master/src/cli/one_helper/oneprovider_helper.rb
- https://github.com/OpenNebula/one/blob/master/src/cli/one_helper/oneprovision_helper.rb

I still don't clearly see how all of this works. Anyway, It seems to me that this issue is not relevant anymore.
