### ISSUE TITLE
Error creating LDAP user

### ISSUE THREAD

**Issue by maartendq** [OpenNebula/terraform-provider-opennebula#189]
Trying to create an ldap user (using auth_driver ldap and leaving out the password) gives the following error:

Error: OpenNebula error [INTERNAL]: [one.user.allocate] Invalid password, it cannot be empty.

opennebula version: 5.12.8

**Comment by jaypif** [comment]
Hi,

Thanks for your issue and sorry for the late answer.

Actually the issue is not on the provider but in the API from OpenNebula. The call `one.user.allocate` expect a password even for `ldap` driver while it is not necessary in that case.

I opened an issue on github to check with them if a fix can be done for 5.12 release: https://github.com/OpenNebula/one/issues/5676

Best regards

**Comment by maartendq** [comment]
Thanks for looking into this! Will follow up on the ONE issue
