### ISSUE TITLE
can i use terraform to snapshot-revert vm?

### ISSUE THREAD

**Issue by vast0906** [OpenNebula/terraform-provider-opennebula#201]
hello,  i want to snapshot-revert vm, I looked at the [terraform providers OpenNebula documentation](https://registry.terraform.io/providers/OpenNebula/opennebula/latest/docs/resources/virtual_machine) 
and looked the [opennebula documentation](https://docs.opennebula.io/5.12/integration/system_interfaces/api.html#onevm) , but not found use terraform to snapshot-revert vm.
can you help me?

**Comment by treywelsh** [comment]
The provider doesn't allow to manage all operations. There is not even a snapshot resource.Actually it's out of it's scope, we try to implement all resources and make them usable.
Even if it would be possible I don't know if it would be a good idea or not to manage snapshots via terraform.

At least if you have some external provider examples

**Comment by treywelsh** [comment]
Hi,

The quick answer is: no, you can't do this for now.

Long answer:
The provider doesn't allow to manage all operations. There is not even a snapshot resource.
For now we try to implement all "first level" resources and make them more convenient to use.

Even if it's possible, I don't know if it would be a good idea or not to manage snapshots and all related operations via terraform, this is a discussion to have around the scope.

I close this issue because it has an answer but if you think it matters to add snapshot management in the provider, feel free to open a new issue with some examples, a proposal etc. around snapshot management
