### ISSUE TITLE
Template: Add FEATURES section and DEV_PREFIX attribute to DISK section

### ISSUE THREAD

**Issue by peterloeffler** [OpenNebula/terraform-provider-opennebula#233]
We have the use case to add the FEATURES section as well as add the DEV_PREFIX attribute to DISK section.
I created a branch https://github.com/peterloeffler/terraform-provider-opennebula/tree/add_features_section_and_dev_prefix_disk_attribute that seems to handle this.
Would it be ok to make a pull request here to get this into the master and in the next version?
Is there something to do it in a better way or to add?

Also looked into adding the attributes CACHE, DISCARD and IO to the DISK section but it seems like it's not available in the OpenNebula package.

**Comment by treywelsh** [comment]
Feel free to open one or more pull requests.
If you want to add a lot of things unless it's almost the same code for several attributes, instead of a huge PR, please open several issues and PRs to split your work, this will be easier for us to work with. It's not a problem to have several issues or PRs if it's justified.

Don't forget in your PRs to update the documentation, CHANGELOG, and if possible to add some tests cases to the acceptance tests. And give a try to your changes before submit them to ensure that you submit something that works.
The more you do at first, the more it will be easy to understand, review, and approve your changes.

When you say
> it seems like it's not available in the OpenNebula package

I suppose that you means there is no `shared.XXX` to use like this: `dev_prefix, _ := disk.Get(shared.DevPrefix)`
If yes, don't worry, these constants only contains a string, they are only some helpers and it's possible to do the same things only with strings.

Thank you for your involvment

**Comment by peterloeffler** [comment]
pull requests opened:
https://github.com/OpenNebula/terraform-provider-opennebula/pull/242
https://github.com/OpenNebula/terraform-provider-opennebula/pull/237
