### ISSUE TITLE
[resource][VM] Error when updating a volatile disk

### ISSUE THREAD

**Issue by christian7007** [OpenNebula/terraform-provider-opennebula#239]
Acceptance tests are failing wit the error below, because no default value is defined for `volatile_format` attribute:

```
=== RUN   TestAccVirtualMachineDiskUpdate
    testing.go:654: Step 1 error: After applying this step, the plan was not empty:
        
        DIFF:
        
        UPDATE: opennebula_virtual_machine.test
          ...
          disk.0.target:          "vda" => "vda"
          disk.0.volatile_format: "raw" => ""
          disk.0.volatile_type:   "swap" => "swap"
          ...
        
        STATE:
        
        opennebula_image.image1:
          ...
        opennebula_image.image2:
          ...
        opennebula_virtual_machine.test:
          ...
          disk.0.target = vda
          disk.0.volatile_format = raw
          disk.0.volatile_type = swap
          ...
--- FAIL: TestAccVirtualMachineDiskUpdate (63.85s)
```

I think the problem is in the `volatile_format` definition, as no default value is set but the validate function will fail if the value is not include in `validtypes`, hence it will fails when the value is empty:

```
"volatile_format": {
	Type:        schema.TypeString,
	Optional:    true,
	Description: "Format of the volatile disk: raw or qcow2.",
	ValidateFunc: func(v interface{}, k string) (ws []string, errors []error) {
		validtypes := []string{"raw", "qcow2"}
		value := v.(string)

		if inArray(value, validtypes) < 0 {
			errors = append(errors, fmt.Errorf("Format %q must be one of: %s", k, strings.Join(validtypes, ",")))
		}

		return
	},
},
```

**Comment by treywelsh** [comment]
To give a bit more of details on this issue, currently the CI repository don't fail on this test, how did you see this one ?

**Comment by christian7007** [comment]
I'm able to reproduce it for OpenNebula 6.2.2 EE. I think the oneflow bug is masking this in the CI tests.

**Comment by treywelsh** [comment]
Looking at #242 comments, it seems that I was too confident and too fast in merging #240 PR, apologies.

For more context:
Volatile disks
- were added by PR #155 
- [are documented here for the 5.12 ONE release](https://docs.opennebula.io/5.12/operation/references/template.html#disks-section)

I just made a test against ONE 5.12 with a minimal VM with a disk attached to an image via the `image_id` attribute like this:
```
resource "opennebula_virtual_machine" "test" {
  name        = "test-vm"
  group       = "oneadmin"
  permissions = "642"
  memory      = 128
  cpu         = 0.5
  context = {
    SET_HOSTNAME = "$NAME"
  }

  disk {
    image_id = 7
    target   = "vdc"
  }

  timeout = 5
}
```

Then I get this error message from the provider:
```
│ Error: disk attritutes image_id can't be defined at the same time as volatile_type or volatile_format
│ 
│   with opennebula_virtual_machine.test,
│   on terraform.tf line 240, in resource "opennebula_virtual_machine" "test":
│  240: resource "opennebula_virtual_machine" "test" {
```
It's due to a provider side check I added in #155. 
I tried to remove the check manually, then compile the provider and apply again: the disk is created, attached to the image, and with this in the template:
```
DISK = [
  ...
  FORMAT = "raw",
  ...
 ]
```
I tried to prevent a case with a check (to not mix attribute from disk and volatile disk) but in fact that don't make ONE fail.

I may revert the fix, then try to find a way to test the provider against the 6.2 releases of OpenNebula.

**Comment by treywelsh** [comment]
This seems due to the fact that when using a volatile disk with the attribute `volatile_type` defined, but without `volatile_format` attribute defined, the `volatile_format` is set by default by ONE to `raw` (`volatile_format` has only Optional behavior).
So the provider read the value, set it in `volatile_format`. But the user hasn't defined this attribute so the provider see a diff and want to make an update at next apply.

`volatile_format` shouldn't be have a default value set in every case, I don't find a way to conditionally define a default value.

The appropriate solutions (without re-designing of disks and nics sub resources) would probably be to add the `computed` behavior on `volatile_format`, but having optional+computed is a complex behavior to deal with. In the past we already encoutered some problems (see https://github.com/OpenNebula/terraform-provider-opennebula/pull/80#issuecomment-732308720) but we were working with an old SDK).
It may be interesting to investigate on this to check if things have evolved with SDK v2.

The solutions used until now were to split optional and computed behavior each in a dedicated attribute.
This would mean here to add a `computed_volatile_format` with computed behavior only and used to receive cloud side values. Then the read of `volatile_format`  would be conditional, the condition being that we read the attribute only when the user define it (to be sure that the correct value was applied).

**Comment by treywelsh** [comment]
#260  merged
