### ISSUE TITLE
[0.5.1] import and refresh populate fields with invalid "null" value

### ISSUE THREAD

**Issue by danimo** [OpenNebula/terraform-provider-opennebula#312]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.2

### Affected Resource(s)

- opennebula_virtual_machine

### Expected Behavior

`terraform import` and `terraform refresh` import values with a meaningful default

### Actual Behavior

`terraform import` and `terraform refresh` set a lot of values to `null`, causing problem during operation. Examples:

during refresh:

* `template_id: null` should be `-1`
* `nic_template: null` should be `[]`
* `disk_template: null` should be `[]`

during import:

* `timeout: null` should be a reasonable numerical value (gets implicitly cast to 0, which means e.g. `terraform destroy` cannot succeed).

Alternatively, the module should handle null values gracefully, but it stands to reason that whatever is in the state should be non-ambiguous.

### Steps to Reproduce

1. Run `terraform refresh` on an inventory created with an older version
2. Run `terraform import` on an existing machine id

**Comment by treywelsh** [comment]
Until now `template_id`, `template_disk`, `template_nic` are filled at virtual machine creation when instantiating a VM from a template. After that they don't change because they reflect the template used at the VM creation.

I add some reading code to import the `template_id` (in the VM there is a `TEMPLATE_ID` that I may use), however the template content may have changed so I won't fill `template_disk` and `template_nic`.
