### ISSUE TITLE
Timeline for Missing Resources

### ISSUE THREAD

**Issue by benosman** [OpenNebula/terraform-provider-opennebula#4]
Firstly, Congratulations on making this an official terraform provider! :+1:

I am going to be using this for my clusters and lab, and there are a few resources that I would like to see that are currently missing.

The most important ones to me are Hosts, Clusters & Datastores. 

I wondered if these are planned for the near future, and if they are, what kind of timeline is anticipated?

**Comment by jaypif** [comment]
Hi @benosman 

Thank you :)

About the timeline I don't have it yet. The priority is t fix some issues we have in the current version.

Adding ressources is possible but as I am not an employee of OpenNebula and we are using it to deploy Virtual Infrastructure the first version is more about managing virtual infrastructure.
Some Virtual ressources are stil missing such as: Virtual Router and VM Groups.

About Hardware management it is less prior because it can be done easily manually and not as often as VM. What I mean is that when you add a host to an opennebula cluster it is a one time action. It is quite the same about datastore.
The exception is maybe if you use virtual resources as hosts or datastore: example a dynamic cluster.

Are you in that case ? I can think about adding resources you ask for during the first part of 2020.

Regards

**Comment by benosman** [comment]
Hi @jaypif 

Thanks for the reply. 

I see where you are coming from in terms of your priorities, such as the virtual resources. 

Since I've got my hosts set up with open nebula using configuration management, it is the next step to configure the hosts inside open nebula too, especially as since the majority of them don't have a separate private network, I'm using 1 cluster per host to manage the networks easier.

But, as you say it's not something I will need to repeat over and over again, so for now the manual step is no big deal. The virtual network resource you have implemented will be very important for my network structure, so I will be using and testing that shortly!

Thanks for your work on this :)

**Comment by jaypif** [comment]
Hello

Small update about this issue:
Since v0.2.0 following Resources are supported:
- `opennebula_acl`,
- `opennebula_group`,
- `opennebula_image`,
- `opennebula_security_group`,
- `opennebula_template`,
- `opennebula_virtual_data_center`,
- `opennebula_virtual_machine`,
- `opennebula_virtual_network`,
- `opennebula_virtual_machine_group`

In master branch there is already `opennebula_user` resource  and lots of improvements  (attach / detach disk on VM, Holding IP for virtual network)
We are also working on an issue to attach / detach nic on VMs
About VRouter integration We can try to also add something for the v0.3.0 release

**Comment by treywelsh** [comment]
See PR #170 for a vrouter resource integration proposal
