### ISSUE TITLE
Extend "os" section, adding other OS sub-attributes in opennebula_template

### ISSUE THREAD

**Issue by sam-wouters** [OpenNebula/terraform-provider-opennebula#558]
### Description

Currently only ARCH and BOOT sub-attributes are accepted in the os section, when trying to set other os sub-attributes using template_sections, this results in a change on every terraform plan.

### New or affected resources and data sources

opennebula_template

### Potential terraform configuration

```HCL
os {
  arch = "x86°64"
  boot = ""
  firmware = "/usr/share/OVMF/OVMF_CODE.secboot.fd"
  firmware_secure = true
  machine = "q35" 
}
```

**Comment by jaypif** [comment]
Can we re open this issue as this is required to some VM with UEFI boot in the OS

thanks

**Comment by jschoewe** [comment]
Why does this keep getting stale and closed? Some of us have templates that need secure boot enabled in order to boot them after they're cloned. The work looks done, these fields were added to the one GOCA 2 months ago:
https://github.com/OpenNebula/one/pull/6795
https://github.com/OpenNebula/one/issues/6782

That issue was closed and added to the latest enterprise release (6.10.2) a month ago:
https://github.com/OpenNebula/one/milestone/80?closed=1

I cloned the following branch from this provider, merged master into it, built the provider using this updated code, and tested it on Open Nebula 6.10.2:
https://github.com/OpenNebula/terraform-provider-opennebula/pull/579

It works great, I also tested on an earlier version (6.10.0) and that still works too. These new fields aren't required, this PR doesn't contain breaking changes, building and using a forked provider is a pain, people have been waiting months for this, I don't see any reason not to merge it anymore.

Merge this now please!

&nbsp;
Testing:

Open Nebula version:
![Image](https://github.com/user-attachments/assets/a5edf340-e15f-41a3-ba25-e04846503b59)

Terraform apply result:
![Image](https://github.com/user-attachments/assets/85c0ad6b-2972-4330-8d86-ea9227fa7f7d)

Cloned template new OS fields 6.10.2:
![Image](https://github.com/user-attachments/assets/7da4dc09-981d-4249-bb58-c40c1eeee008)

The OS fields for older versions will look like this and still work:
![Image](https://github.com/user-attachments/assets/4a36388e-05ee-47be-ac9c-92bb96bcdae2)
