### ISSUE TITLE
Second call to `terraform apply` removes disk

### ISSUE THREAD

**Issue by baverman** [OpenNebula/terraform-provider-opennebula#97]
Provider version: 0.3

I have a simple resource:

```
resource "opennebula_virtual_machine" "test1" {
  name = "bobrov-test1"
  cpu = 1
  vcpu = 1
  memory = 1024
  group = "mygroup"
  template_id = data.opennebula_template.centos7.id

  nic {
    network_id = data.opennebula_virtual_network.mynetwork.id
  }
}
```

First `terraform apply` creates VM successfully. By if I run apply second time it deletes my disk:

```
  # opennebula_virtual_machine.test1 will be updated in-place
  ~ resource "opennebula_virtual_machine" "test1" {
        id          = "1990584"
        name        = "bobrov-test1"
        # (15 unchanged attributes hidden)

      - disk {
          - computed_driver = "raw" -> null
          - computed_size   = 10240 -> null
          - computed_target = "vda" -> null
          - disk_id         = 0 -> null
          - image_id        = 13305 -> null
          - size            = 0 -> null
        }


        # (2 unchanged blocks hidden)
    }
```

**Comment by jaypif** [comment]
Hi @baverman 

Can you confirm disk are already present in your template ?
I think this is beacuse your disk is already in the template. As it is not explicitly declare in the VM when you apply a second time, the provider consider the VM has no disk and it detach all disks.

If this is the case, it means there is also the same issue with NIC.

For readability and maintenability it is better to have disk explicitely declare in the VM instead of template. However the current behavior is a bug and the provider must be fixed to not remove elements (disks, nic) from a VM in that case.

**Comment by baverman** [comment]
> Can you confirm disk are already present in your template ?

Yes. Template is defined with a disk.

> For readability and maintenability it is better to have disk explicitely declare in the VM instead of template.

I will be glad to use disk image but our current setup assumes some context boot hda device and I did not managed to create a working VM without a template.

**Comment by treywelsh** [comment]
Thank you for reporting this,

This is not a behavior specific to disks and NICs, unexpected things could happen later for other VM parts (OS, graphics etc...) added via the template _only_ and with an update behavior.

You're in the only case that trigger the problem:
At VM creation, with a `template_id`, the parts described in the tf file will overwrite template parts. (putting disk in tf file will overwrite disk descriptions from the template. The only part that has a custom behavior is the context part).

This problem is triggered by the diff that terraform see on disk attribute.
In the VM schema, disk type is `TypeList`, but when reading VM description there is no distinction made between a disk added via the template, and those added via the tf file.

To avoid this diff my first idea was to try to customize the diff via `CustomizeDiffFunc`, however terraform diff tooling doesn't seems to be enough accurate to remove partial diff.
This seems too complex/inaccurate to implement for now. (As a side note, we aren't up to date in this provider, we don't use the last terraform SDK versions)

Another way to do, is to modify the VM schema and read step to differentiate how we process the disk added via the template, and the disk added via the TF file.
Here is my draft PR, I made some manual tests and it seems to work, feel free to test it and drop comments about it: #100  
In brief, disk and NIC added via the template are added in a separated list filled at VM creation.
However it's not possible anymore to detach them later.

It's important to note that this last solution add a bit more of complexity to the VM resource implementation around disk and NIC, which is already complex.
The whole complexity is due to the fact that they are list of schemas and it's not so easy to work with.
So, an other solution that I have to mention (already mentioned [here](https://github.com/OpenNebula/terraform-provider-opennebula/pull/80#issuecomment-732308720)) is:
Instead of having a complex VM resource with all stuffs included and with complex update behaviors, we could introduce `opennebula_virtual_machine_nic` and `opennebula_virtual_machine_disk` resources.
This would split VM schema and related code among several resources which would be more simple.
Disks and NIC provided via the template could be immutable, in the same way that I considered above so I'm not sure that we would loose something with this last approach.
Here is an old draft [branch that externalize NIC ressource attachment](https://github.com/treywelsh/terraform-provider-opennebula/tree/F-72-new-ressource-nic)
The problem is that this would break a bit the current provider architecture
